// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/requestResponse.proto

package com.inmobi.databus.visualization.shared;

public final class RequestResponse {
  private RequestResponse() {}
  
  public static final class Request extends
      com.google.protobuf.gwt.shared.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {
      initFields();
    }
    
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .GraphDataRequest graphDataRequest = 1;
    public static final int GRAPHDATAREQUEST_FIELD_NUMBER = 1;
    private boolean hasGraphDataRequest;
    @com.google.protobuf.gwt.shared.FieldNumber(1)
    private com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest graphDataRequest_;
    public boolean hasGraphDataRequest() { return hasGraphDataRequest; }
    public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest getGraphDataRequest() { return graphDataRequest_; }
    
    private void initFields() {
      graphDataRequest_ = com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.getDefaultInstance();
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.gwt.shared.JsonStream output)
      throws java.io.IOException {
      
      if (hasGraphDataRequest()) {
        output.writeMessage(1, "graphDataRequest", getGraphDataRequest());
      }
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inmobi.databus.visualization.shared.RequestResponse.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.gwt.shared.GeneratedMessage.Builder<
          com.inmobi.databus.visualization.shared.RequestResponse.Request, Builder> {
      
      private com.inmobi.databus.visualization.shared.RequestResponse.Request result;
      
      // Construct using com.inmobi.databus.visualization.shared.RequestResponse.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.inmobi.databus.visualization.shared.RequestResponse.Request();
        return builder;
      }
      
      protected com.inmobi.databus.visualization.shared.RequestResponse.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.inmobi.databus.visualization.shared.RequestResponse.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Request getDefaultInstanceForType() {
        return com.inmobi.databus.visualization.shared.RequestResponse.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Request buildParsed()
          throws com.google.protobuf.gwt.shared.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Request buildPartial() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.inmobi.databus.visualization.shared.RequestResponse.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.gwt.shared.Message other) {
        if (other instanceof com.inmobi.databus.visualization.shared.RequestResponse.Request) {
          return mergeFrom((com.inmobi.databus.visualization.shared.RequestResponse.Request)other);
        }
        return this;
      }
      
      public Builder mergeFrom(com.inmobi.databus.visualization.shared.RequestResponse.Request other) {
        if (other == com.inmobi.databus.visualization.shared.RequestResponse.Request.getDefaultInstance()) return this;
        
        if (other.hasGraphDataRequest()) {
          mergeGraphDataRequest(other.getGraphDataRequest());
        }
      
        return this;
      }
      
      public Builder readFrom(com.google.protobuf.gwt.shared.JsonStream input)
        throws java.io.IOException {
        
        com.google.protobuf.gwt.shared.JsonStream graphDataRequestJson = input.readStream(1);
        if (graphDataRequestJson != null) {
          com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.Builder graphDataRequestBuilder = com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.newBuilder();
          if (hasGraphDataRequest()) {
            graphDataRequestBuilder.mergeFrom(getGraphDataRequest());
          }
          graphDataRequestBuilder.readFrom(graphDataRequestJson);
          setGraphDataRequest(graphDataRequestBuilder.buildParsed());
        }
        
        return this;
      }
      
      // optional .GraphDataRequest graphDataRequest = 1;
      public boolean hasGraphDataRequest() {
        return result.hasGraphDataRequest();
      }
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest getGraphDataRequest() {
        return result.getGraphDataRequest();
      }
      public Builder setGraphDataRequest(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest value) {
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        result.hasGraphDataRequest = true;
        result.graphDataRequest_ = value;
        return this;
      }
      public Builder setGraphDataRequest(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.Builder builderForValue) {
        result.hasGraphDataRequest = true;
        result.graphDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGraphDataRequest(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest value) {
        if (result.hasGraphDataRequest() &&
            result.graphDataRequest_ != com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.getDefaultInstance()) {
          result.graphDataRequest_ =
            com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.newBuilder(result.graphDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.graphDataRequest_ = value;
        }
        result.hasGraphDataRequest = true;
        return this;
      }
      public Builder clearGraphDataRequest() {
        result.hasGraphDataRequest = false;
        result.graphDataRequest_ = com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Request)
    }
    
    static {
      defaultInstance = new Request(true);
      com.inmobi.databus.visualization.shared.RequestResponse.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Request)
  }
  
  public static final class GraphDataRequest extends
      com.google.protobuf.gwt.shared.GeneratedMessage {
    // Use GraphDataRequest.newBuilder() to construct.
    private GraphDataRequest() {
      initFields();
    }
    
    private GraphDataRequest(boolean noInit) {}
    
    private static final GraphDataRequest defaultInstance;
    public static GraphDataRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public GraphDataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional string stream = 1;
    public static final int STREAM_FIELD_NUMBER = 1;
    private boolean hasStream;
    @com.google.protobuf.gwt.shared.FieldNumber(1)
    private java.lang.String stream_ = "";
    public boolean hasStream() { return hasStream; }
    public java.lang.String getStream() { return stream_; }
    
    // optional string colo = 2;
    public static final int COLO_FIELD_NUMBER = 2;
    private boolean hasColo;
    @com.google.protobuf.gwt.shared.FieldNumber(2)
    private java.lang.String colo_ = "";
    public boolean hasColo() { return hasColo; }
    public java.lang.String getColo() { return colo_; }
    
    // optional string startTime = 3;
    public static final int STARTTIME_FIELD_NUMBER = 3;
    private boolean hasStartTime;
    @com.google.protobuf.gwt.shared.FieldNumber(3)
    private java.lang.String startTime_ = "";
    public boolean hasStartTime() { return hasStartTime; }
    public java.lang.String getStartTime() { return startTime_; }
    
    // optional string endTime = 4;
    public static final int ENDTIME_FIELD_NUMBER = 4;
    private boolean hasEndTime;
    @com.google.protobuf.gwt.shared.FieldNumber(4)
    private java.lang.String endTime_ = "";
    public boolean hasEndTime() { return hasEndTime; }
    public java.lang.String getEndTime() { return endTime_; }
    
    private void initFields() {
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.gwt.shared.JsonStream output)
      throws java.io.IOException {
      
      if (hasStream()) {
        output.writeString(1, "stream", getStream());
      }
      
      if (hasColo()) {
        output.writeString(2, "colo", getColo());
      }
      
      if (hasStartTime()) {
        output.writeString(3, "startTime", getStartTime());
      }
      
      if (hasEndTime()) {
        output.writeString(4, "endTime", getEndTime());
      }
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.gwt.shared.GeneratedMessage.Builder<
          com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest, Builder> {
      
      private com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest result;
      
      // Construct using com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest();
        return builder;
      }
      
      protected com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest getDefaultInstanceForType() {
        return com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest buildParsed()
          throws com.google.protobuf.gwt.shared.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest buildPartial() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.gwt.shared.Message other) {
        if (other instanceof com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest) {
          return mergeFrom((com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest)other);
        }
        return this;
      }
      
      public Builder mergeFrom(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest other) {
        if (other == com.inmobi.databus.visualization.shared.RequestResponse.GraphDataRequest.getDefaultInstance()) return this;
        
        if (other.hasStream()) {
          setStream(other.getStream());
        }
        
        if (other.hasColo()) {
          setColo(other.getColo());
        }
        
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
      
        return this;
      }
      
      public Builder readFrom(com.google.protobuf.gwt.shared.JsonStream input)
        throws java.io.IOException {
        
        java.lang.String stream = input.readString(1);
        if (stream != null) {
          setStream(stream);
        }
        
        java.lang.String colo = input.readString(2);
        if (colo != null) {
          setColo(colo);
        }
        
        java.lang.String startTime = input.readString(3);
        if (startTime != null) {
          setStartTime(startTime);
        }
        
        java.lang.String endTime = input.readString(4);
        if (endTime != null) {
          setEndTime(endTime);
        }
        
        return this;
      }
      
      // optional string stream = 1;
      public boolean hasStream() {
        return result.hasStream();
      }
      public java.lang.String getStream() {
        return result.getStream();
      }
      public Builder setStreamIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          setStream(value);
        }
        return this;
      }
      public Builder setStream(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.hasStream = true;
        result.stream_ = value;
        return this;
      }
      public Builder clearStream() {
        result.hasStream = false;
        result.stream_ = getDefaultInstance().getStream();
        return this;
      }
      
      // optional string colo = 2;
      public boolean hasColo() {
        return result.hasColo();
      }
      public java.lang.String getColo() {
        return result.getColo();
      }
      public Builder setColoIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          setColo(value);
        }
        return this;
      }
      public Builder setColo(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.hasColo = true;
        result.colo_ = value;
        return this;
      }
      public Builder clearColo() {
        result.hasColo = false;
        result.colo_ = getDefaultInstance().getColo();
        return this;
      }
      
      // optional string startTime = 3;
      public boolean hasStartTime() {
        return result.hasStartTime();
      }
      public java.lang.String getStartTime() {
        return result.getStartTime();
      }
      public Builder setStartTimeIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          setStartTime(value);
        }
        return this;
      }
      public Builder setStartTime(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.hasStartTime = true;
        result.startTime_ = value;
        return this;
      }
      public Builder clearStartTime() {
        result.hasStartTime = false;
        result.startTime_ = getDefaultInstance().getStartTime();
        return this;
      }
      
      // optional string endTime = 4;
      public boolean hasEndTime() {
        return result.hasEndTime();
      }
      public java.lang.String getEndTime() {
        return result.getEndTime();
      }
      public Builder setEndTimeIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          setEndTime(value);
        }
        return this;
      }
      public Builder setEndTime(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.hasEndTime = true;
        result.endTime_ = value;
        return this;
      }
      public Builder clearEndTime() {
        result.hasEndTime = false;
        result.endTime_ = getDefaultInstance().getEndTime();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:GraphDataRequest)
    }
    
    static {
      defaultInstance = new GraphDataRequest(true);
      com.inmobi.databus.visualization.shared.RequestResponse.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GraphDataRequest)
  }
  
  public static final class Response extends
      com.google.protobuf.gwt.shared.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {
      initFields();
    }
    
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional .GraphDataResponse graphDataResponse = 1;
    public static final int GRAPHDATARESPONSE_FIELD_NUMBER = 1;
    private boolean hasGraphDataResponse;
    @com.google.protobuf.gwt.shared.FieldNumber(1)
    private com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse graphDataResponse_;
    public boolean hasGraphDataResponse() { return hasGraphDataResponse; }
    public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse getGraphDataResponse() { return graphDataResponse_; }
    
    // optional .LoadMainPanelResponse loadMainPanelResponse = 2;
    public static final int LOADMAINPANELRESPONSE_FIELD_NUMBER = 2;
    private boolean hasLoadMainPanelResponse;
    @com.google.protobuf.gwt.shared.FieldNumber(2)
    private com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse loadMainPanelResponse_;
    public boolean hasLoadMainPanelResponse() { return hasLoadMainPanelResponse; }
    public com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse getLoadMainPanelResponse() { return loadMainPanelResponse_; }
    
    private void initFields() {
      graphDataResponse_ = com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.getDefaultInstance();
      loadMainPanelResponse_ = com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.getDefaultInstance();
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.gwt.shared.JsonStream output)
      throws java.io.IOException {
      
      if (hasGraphDataResponse()) {
        output.writeMessage(1, "graphDataResponse", getGraphDataResponse());
      }
      
      if (hasLoadMainPanelResponse()) {
        output.writeMessage(2, "loadMainPanelResponse", getLoadMainPanelResponse());
      }
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inmobi.databus.visualization.shared.RequestResponse.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.gwt.shared.GeneratedMessage.Builder<
          com.inmobi.databus.visualization.shared.RequestResponse.Response, Builder> {
      
      private com.inmobi.databus.visualization.shared.RequestResponse.Response result;
      
      // Construct using com.inmobi.databus.visualization.shared.RequestResponse.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.inmobi.databus.visualization.shared.RequestResponse.Response();
        return builder;
      }
      
      protected com.inmobi.databus.visualization.shared.RequestResponse.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.inmobi.databus.visualization.shared.RequestResponse.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Response getDefaultInstanceForType() {
        return com.inmobi.databus.visualization.shared.RequestResponse.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Response buildParsed()
          throws com.google.protobuf.gwt.shared.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.Response buildPartial() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.inmobi.databus.visualization.shared.RequestResponse.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.gwt.shared.Message other) {
        if (other instanceof com.inmobi.databus.visualization.shared.RequestResponse.Response) {
          return mergeFrom((com.inmobi.databus.visualization.shared.RequestResponse.Response)other);
        }
        return this;
      }
      
      public Builder mergeFrom(com.inmobi.databus.visualization.shared.RequestResponse.Response other) {
        if (other == com.inmobi.databus.visualization.shared.RequestResponse.Response.getDefaultInstance()) return this;
        
        if (other.hasGraphDataResponse()) {
          mergeGraphDataResponse(other.getGraphDataResponse());
        }
        
        if (other.hasLoadMainPanelResponse()) {
          mergeLoadMainPanelResponse(other.getLoadMainPanelResponse());
        }
      
        return this;
      }
      
      public Builder readFrom(com.google.protobuf.gwt.shared.JsonStream input)
        throws java.io.IOException {
        
        com.google.protobuf.gwt.shared.JsonStream graphDataResponseJson = input.readStream(1);
        if (graphDataResponseJson != null) {
          com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.Builder graphDataResponseBuilder = com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.newBuilder();
          if (hasGraphDataResponse()) {
            graphDataResponseBuilder.mergeFrom(getGraphDataResponse());
          }
          graphDataResponseBuilder.readFrom(graphDataResponseJson);
          setGraphDataResponse(graphDataResponseBuilder.buildParsed());
        }
        
        com.google.protobuf.gwt.shared.JsonStream loadMainPanelResponseJson = input.readStream(2);
        if (loadMainPanelResponseJson != null) {
          com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.Builder loadMainPanelResponseBuilder = com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.newBuilder();
          if (hasLoadMainPanelResponse()) {
            loadMainPanelResponseBuilder.mergeFrom(getLoadMainPanelResponse());
          }
          loadMainPanelResponseBuilder.readFrom(loadMainPanelResponseJson);
          setLoadMainPanelResponse(loadMainPanelResponseBuilder.buildParsed());
        }
        
        return this;
      }
      
      // optional .GraphDataResponse graphDataResponse = 1;
      public boolean hasGraphDataResponse() {
        return result.hasGraphDataResponse();
      }
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse getGraphDataResponse() {
        return result.getGraphDataResponse();
      }
      public Builder setGraphDataResponse(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse value) {
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        result.hasGraphDataResponse = true;
        result.graphDataResponse_ = value;
        return this;
      }
      public Builder setGraphDataResponse(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.Builder builderForValue) {
        result.hasGraphDataResponse = true;
        result.graphDataResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeGraphDataResponse(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse value) {
        if (result.hasGraphDataResponse() &&
            result.graphDataResponse_ != com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.getDefaultInstance()) {
          result.graphDataResponse_ =
            com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.newBuilder(result.graphDataResponse_).mergeFrom(value).buildPartial();
        } else {
          result.graphDataResponse_ = value;
        }
        result.hasGraphDataResponse = true;
        return this;
      }
      public Builder clearGraphDataResponse() {
        result.hasGraphDataResponse = false;
        result.graphDataResponse_ = com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.getDefaultInstance();
        return this;
      }
      
      // optional .LoadMainPanelResponse loadMainPanelResponse = 2;
      public boolean hasLoadMainPanelResponse() {
        return result.hasLoadMainPanelResponse();
      }
      public com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse getLoadMainPanelResponse() {
        return result.getLoadMainPanelResponse();
      }
      public Builder setLoadMainPanelResponse(com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse value) {
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        result.hasLoadMainPanelResponse = true;
        result.loadMainPanelResponse_ = value;
        return this;
      }
      public Builder setLoadMainPanelResponse(com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.Builder builderForValue) {
        result.hasLoadMainPanelResponse = true;
        result.loadMainPanelResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoadMainPanelResponse(com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse value) {
        if (result.hasLoadMainPanelResponse() &&
            result.loadMainPanelResponse_ != com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.getDefaultInstance()) {
          result.loadMainPanelResponse_ =
            com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.newBuilder(result.loadMainPanelResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loadMainPanelResponse_ = value;
        }
        result.hasLoadMainPanelResponse = true;
        return this;
      }
      public Builder clearLoadMainPanelResponse() {
        result.hasLoadMainPanelResponse = false;
        result.loadMainPanelResponse_ = com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Response)
    }
    
    static {
      defaultInstance = new Response(true);
      com.inmobi.databus.visualization.shared.RequestResponse.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Response)
  }
  
  public static final class GraphDataResponse extends
      com.google.protobuf.gwt.shared.GeneratedMessage {
    // Use GraphDataResponse.newBuilder() to construct.
    private GraphDataResponse() {
      initFields();
    }
    
    private GraphDataResponse(boolean noInit) {}
    
    private static final GraphDataResponse defaultInstance;
    public static GraphDataResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public GraphDataResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional string jsonString = 1;
    public static final int JSONSTRING_FIELD_NUMBER = 1;
    private boolean hasJsonString;
    @com.google.protobuf.gwt.shared.FieldNumber(1)
    private java.lang.String jsonString_ = "";
    public boolean hasJsonString() { return hasJsonString; }
    public java.lang.String getJsonString() { return jsonString_; }
    
    // optional int32 agentSla = 2;
    public static final int AGENTSLA_FIELD_NUMBER = 2;
    private boolean hasAgentSla;
    @com.google.protobuf.gwt.shared.FieldNumber(2)
    private int agentSla_ = 0;
    public boolean hasAgentSla() { return hasAgentSla; }
    public int getAgentSla() { return agentSla_; }
    
    // optional int32 vipSla = 3;
    public static final int VIPSLA_FIELD_NUMBER = 3;
    private boolean hasVipSla;
    @com.google.protobuf.gwt.shared.FieldNumber(3)
    private int vipSla_ = 0;
    public boolean hasVipSla() { return hasVipSla; }
    public int getVipSla() { return vipSla_; }
    
    // optional int32 collectorSla = 4;
    public static final int COLLECTORSLA_FIELD_NUMBER = 4;
    private boolean hasCollectorSla;
    @com.google.protobuf.gwt.shared.FieldNumber(4)
    private int collectorSla_ = 0;
    public boolean hasCollectorSla() { return hasCollectorSla; }
    public int getCollectorSla() { return collectorSla_; }
    
    // optional int32 hdfsSla = 5;
    public static final int HDFSSLA_FIELD_NUMBER = 5;
    private boolean hasHdfsSla;
    @com.google.protobuf.gwt.shared.FieldNumber(5)
    private int hdfsSla_ = 0;
    public boolean hasHdfsSla() { return hasHdfsSla; }
    public int getHdfsSla() { return hdfsSla_; }
    
    // optional int32 localSla = 6;
    public static final int LOCALSLA_FIELD_NUMBER = 6;
    private boolean hasLocalSla;
    @com.google.protobuf.gwt.shared.FieldNumber(6)
    private int localSla_ = 0;
    public boolean hasLocalSla() { return hasLocalSla; }
    public int getLocalSla() { return localSla_; }
    
    // optional int32 mergeSla = 7;
    public static final int MERGESLA_FIELD_NUMBER = 7;
    private boolean hasMergeSla;
    @com.google.protobuf.gwt.shared.FieldNumber(7)
    private int mergeSla_ = 0;
    public boolean hasMergeSla() { return hasMergeSla; }
    public int getMergeSla() { return mergeSla_; }
    
    // optional int32 mirrorSla = 8;
    public static final int MIRRORSLA_FIELD_NUMBER = 8;
    private boolean hasMirrorSla;
    @com.google.protobuf.gwt.shared.FieldNumber(8)
    private int mirrorSla_ = 0;
    public boolean hasMirrorSla() { return hasMirrorSla; }
    public int getMirrorSla() { return mirrorSla_; }
    
    // optional float percentileForSla = 9;
    public static final int PERCENTILEFORSLA_FIELD_NUMBER = 9;
    private boolean hasPercentileForSla;
    @com.google.protobuf.gwt.shared.FieldNumber(9)
    private float percentileForSla_ = 0F;
    public boolean hasPercentileForSla() { return hasPercentileForSla; }
    public float getPercentileForSla() { return percentileForSla_; }
    
    // optional float percentageForLoss = 10;
    public static final int PERCENTAGEFORLOSS_FIELD_NUMBER = 10;
    private boolean hasPercentageForLoss;
    @com.google.protobuf.gwt.shared.FieldNumber(10)
    private float percentageForLoss_ = 0F;
    public boolean hasPercentageForLoss() { return hasPercentageForLoss; }
    public float getPercentageForLoss() { return percentageForLoss_; }
    
    private void initFields() {
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.gwt.shared.JsonStream output)
      throws java.io.IOException {
      
      if (hasJsonString()) {
        output.writeString(1, "jsonString", getJsonString());
      }
      
      if (hasAgentSla()) {
        output.writeInteger(2, "agentSla", getAgentSla());
      }
      
      if (hasVipSla()) {
        output.writeInteger(3, "vipSla", getVipSla());
      }
      
      if (hasCollectorSla()) {
        output.writeInteger(4, "collectorSla", getCollectorSla());
      }
      
      if (hasHdfsSla()) {
        output.writeInteger(5, "hdfsSla", getHdfsSla());
      }
      
      if (hasLocalSla()) {
        output.writeInteger(6, "localSla", getLocalSla());
      }
      
      if (hasMergeSla()) {
        output.writeInteger(7, "mergeSla", getMergeSla());
      }
      
      if (hasMirrorSla()) {
        output.writeInteger(8, "mirrorSla", getMirrorSla());
      }
      
      if (hasPercentileForSla()) {
        output.writeFloat(9, "percentileForSla", getPercentileForSla());
      }
      
      if (hasPercentageForLoss()) {
        output.writeFloat(10, "percentageForLoss", getPercentageForLoss());
      }
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.gwt.shared.GeneratedMessage.Builder<
          com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse, Builder> {
      
      private com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse result;
      
      // Construct using com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse();
        return builder;
      }
      
      protected com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse getDefaultInstanceForType() {
        return com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse buildParsed()
          throws com.google.protobuf.gwt.shared.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse buildPartial() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.gwt.shared.Message other) {
        if (other instanceof com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse) {
          return mergeFrom((com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse)other);
        }
        return this;
      }
      
      public Builder mergeFrom(com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse other) {
        if (other == com.inmobi.databus.visualization.shared.RequestResponse.GraphDataResponse.getDefaultInstance()) return this;
        
        if (other.hasJsonString()) {
          setJsonString(other.getJsonString());
        }
        
        if (other.hasAgentSla()) {
          setAgentSla(other.getAgentSla());
        }
        
        if (other.hasVipSla()) {
          setVipSla(other.getVipSla());
        }
        
        if (other.hasCollectorSla()) {
          setCollectorSla(other.getCollectorSla());
        }
        
        if (other.hasHdfsSla()) {
          setHdfsSla(other.getHdfsSla());
        }
        
        if (other.hasLocalSla()) {
          setLocalSla(other.getLocalSla());
        }
        
        if (other.hasMergeSla()) {
          setMergeSla(other.getMergeSla());
        }
        
        if (other.hasMirrorSla()) {
          setMirrorSla(other.getMirrorSla());
        }
        
        if (other.hasPercentileForSla()) {
          setPercentileForSla(other.getPercentileForSla());
        }
        
        if (other.hasPercentageForLoss()) {
          setPercentageForLoss(other.getPercentageForLoss());
        }
      
        return this;
      }
      
      public Builder readFrom(com.google.protobuf.gwt.shared.JsonStream input)
        throws java.io.IOException {
        
        java.lang.String jsonString = input.readString(1);
        if (jsonString != null) {
          setJsonString(jsonString);
        }
        
        java.lang.Integer agentSla = input.readInteger(2);
        if (agentSla != null) {
          setAgentSla(agentSla);
        }
        
        java.lang.Integer vipSla = input.readInteger(3);
        if (vipSla != null) {
          setVipSla(vipSla);
        }
        
        java.lang.Integer collectorSla = input.readInteger(4);
        if (collectorSla != null) {
          setCollectorSla(collectorSla);
        }
        
        java.lang.Integer hdfsSla = input.readInteger(5);
        if (hdfsSla != null) {
          setHdfsSla(hdfsSla);
        }
        
        java.lang.Integer localSla = input.readInteger(6);
        if (localSla != null) {
          setLocalSla(localSla);
        }
        
        java.lang.Integer mergeSla = input.readInteger(7);
        if (mergeSla != null) {
          setMergeSla(mergeSla);
        }
        
        java.lang.Integer mirrorSla = input.readInteger(8);
        if (mirrorSla != null) {
          setMirrorSla(mirrorSla);
        }
        
        java.lang.Float percentileForSla = input.readFloat(9);
        if (percentileForSla != null) {
          setPercentileForSla(percentileForSla);
        }
        
        java.lang.Float percentageForLoss = input.readFloat(10);
        if (percentageForLoss != null) {
          setPercentageForLoss(percentageForLoss);
        }
        
        return this;
      }
      
      // optional string jsonString = 1;
      public boolean hasJsonString() {
        return result.hasJsonString();
      }
      public java.lang.String getJsonString() {
        return result.getJsonString();
      }
      public Builder setJsonStringIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          setJsonString(value);
        }
        return this;
      }
      public Builder setJsonString(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.hasJsonString = true;
        result.jsonString_ = value;
        return this;
      }
      public Builder clearJsonString() {
        result.hasJsonString = false;
        result.jsonString_ = getDefaultInstance().getJsonString();
        return this;
      }
      
      // optional int32 agentSla = 2;
      public boolean hasAgentSla() {
        return result.hasAgentSla();
      }
      public int getAgentSla() {
        return result.getAgentSla();
      }
      public Builder setAgentSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setAgentSla(value);
        }
        return this;
      }
      public Builder setAgentSla(int value) {
        result.hasAgentSla = true;
        result.agentSla_ = value;
        return this;
      }
      public Builder clearAgentSla() {
        result.hasAgentSla = false;
        result.agentSla_ = 0;
        return this;
      }
      
      // optional int32 vipSla = 3;
      public boolean hasVipSla() {
        return result.hasVipSla();
      }
      public int getVipSla() {
        return result.getVipSla();
      }
      public Builder setVipSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setVipSla(value);
        }
        return this;
      }
      public Builder setVipSla(int value) {
        result.hasVipSla = true;
        result.vipSla_ = value;
        return this;
      }
      public Builder clearVipSla() {
        result.hasVipSla = false;
        result.vipSla_ = 0;
        return this;
      }
      
      // optional int32 collectorSla = 4;
      public boolean hasCollectorSla() {
        return result.hasCollectorSla();
      }
      public int getCollectorSla() {
        return result.getCollectorSla();
      }
      public Builder setCollectorSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setCollectorSla(value);
        }
        return this;
      }
      public Builder setCollectorSla(int value) {
        result.hasCollectorSla = true;
        result.collectorSla_ = value;
        return this;
      }
      public Builder clearCollectorSla() {
        result.hasCollectorSla = false;
        result.collectorSla_ = 0;
        return this;
      }
      
      // optional int32 hdfsSla = 5;
      public boolean hasHdfsSla() {
        return result.hasHdfsSla();
      }
      public int getHdfsSla() {
        return result.getHdfsSla();
      }
      public Builder setHdfsSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setHdfsSla(value);
        }
        return this;
      }
      public Builder setHdfsSla(int value) {
        result.hasHdfsSla = true;
        result.hdfsSla_ = value;
        return this;
      }
      public Builder clearHdfsSla() {
        result.hasHdfsSla = false;
        result.hdfsSla_ = 0;
        return this;
      }
      
      // optional int32 localSla = 6;
      public boolean hasLocalSla() {
        return result.hasLocalSla();
      }
      public int getLocalSla() {
        return result.getLocalSla();
      }
      public Builder setLocalSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setLocalSla(value);
        }
        return this;
      }
      public Builder setLocalSla(int value) {
        result.hasLocalSla = true;
        result.localSla_ = value;
        return this;
      }
      public Builder clearLocalSla() {
        result.hasLocalSla = false;
        result.localSla_ = 0;
        return this;
      }
      
      // optional int32 mergeSla = 7;
      public boolean hasMergeSla() {
        return result.hasMergeSla();
      }
      public int getMergeSla() {
        return result.getMergeSla();
      }
      public Builder setMergeSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setMergeSla(value);
        }
        return this;
      }
      public Builder setMergeSla(int value) {
        result.hasMergeSla = true;
        result.mergeSla_ = value;
        return this;
      }
      public Builder clearMergeSla() {
        result.hasMergeSla = false;
        result.mergeSla_ = 0;
        return this;
      }
      
      // optional int32 mirrorSla = 8;
      public boolean hasMirrorSla() {
        return result.hasMirrorSla();
      }
      public int getMirrorSla() {
        return result.getMirrorSla();
      }
      public Builder setMirrorSlaIgnoreIfNull(java.lang.Integer value) {
        if (value != null) {
          setMirrorSla(value);
        }
        return this;
      }
      public Builder setMirrorSla(int value) {
        result.hasMirrorSla = true;
        result.mirrorSla_ = value;
        return this;
      }
      public Builder clearMirrorSla() {
        result.hasMirrorSla = false;
        result.mirrorSla_ = 0;
        return this;
      }
      
      // optional float percentileForSla = 9;
      public boolean hasPercentileForSla() {
        return result.hasPercentileForSla();
      }
      public float getPercentileForSla() {
        return result.getPercentileForSla();
      }
      public Builder setPercentileForSlaIgnoreIfNull(java.lang.Float value) {
        if (value != null) {
          setPercentileForSla(value);
        }
        return this;
      }
      public Builder setPercentileForSla(float value) {
        result.hasPercentileForSla = true;
        result.percentileForSla_ = value;
        return this;
      }
      public Builder clearPercentileForSla() {
        result.hasPercentileForSla = false;
        result.percentileForSla_ = 0F;
        return this;
      }
      
      // optional float percentageForLoss = 10;
      public boolean hasPercentageForLoss() {
        return result.hasPercentageForLoss();
      }
      public float getPercentageForLoss() {
        return result.getPercentageForLoss();
      }
      public Builder setPercentageForLossIgnoreIfNull(java.lang.Float value) {
        if (value != null) {
          setPercentageForLoss(value);
        }
        return this;
      }
      public Builder setPercentageForLoss(float value) {
        result.hasPercentageForLoss = true;
        result.percentageForLoss_ = value;
        return this;
      }
      public Builder clearPercentageForLoss() {
        result.hasPercentageForLoss = false;
        result.percentageForLoss_ = 0F;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:GraphDataResponse)
    }
    
    static {
      defaultInstance = new GraphDataResponse(true);
      com.inmobi.databus.visualization.shared.RequestResponse.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GraphDataResponse)
  }
  
  public static final class LoadMainPanelResponse extends
      com.google.protobuf.gwt.shared.GeneratedMessage {
    // Use LoadMainPanelResponse.newBuilder() to construct.
    private LoadMainPanelResponse() {
      initFields();
    }
    
    private LoadMainPanelResponse(boolean noInit) {}
    
    private static final LoadMainPanelResponse defaultInstance;
    public static LoadMainPanelResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoadMainPanelResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated string stream = 1;
    public static final int STREAM_FIELD_NUMBER = 1;
    private java.util.List<java.lang.String> stream_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getStreamList() {
      return stream_;
    }
    public int getStreamCount() { return stream_.size(); }
    public java.lang.String getStream(int index) {
      return stream_.get(index);
    }
    
    // repeated string cluster = 2;
    public static final int CLUSTER_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> cluster_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getClusterList() {
      return cluster_;
    }
    public int getClusterCount() { return cluster_.size(); }
    public java.lang.String getCluster(int index) {
      return cluster_.get(index);
    }
    
    private void initFields() {
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.gwt.shared.JsonStream output)
      throws java.io.IOException {
      
      if (getStreamList().size() > 0) {
        output.writeStringRepeated(1, "stream list", getStreamList());
      }
      
      if (getClusterList().size() > 0) {
        output.writeStringRepeated(2, "cluster list", getClusterList());
      }
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.gwt.shared.GeneratedMessage.Builder<
          com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse, Builder> {
      
      private com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse result;
      
      // Construct using com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse();
        return builder;
      }
      
      protected com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse getDefaultInstanceForType() {
        return com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse buildParsed()
          throws com.google.protobuf.gwt.shared.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse buildPartial() {
        if (result == null) {
          throw new java.lang.IllegalStateException(
            "build() has already been called on this Builder.");
        }
        
        if (result.stream_ != java.util.Collections.EMPTY_LIST) {
          result.stream_ =
            java.util.Collections.unmodifiableList(result.stream_);
        }
        
        if (result.cluster_ != java.util.Collections.EMPTY_LIST) {
          result.cluster_ =
            java.util.Collections.unmodifiableList(result.cluster_);
        }
        com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.gwt.shared.Message other) {
        if (other instanceof com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse) {
          return mergeFrom((com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse)other);
        }
        return this;
      }
      
      public Builder mergeFrom(com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse other) {
        if (other == com.inmobi.databus.visualization.shared.RequestResponse.LoadMainPanelResponse.getDefaultInstance()) return this;
        
        if (!other.stream_.isEmpty()) {
          if (result.stream_.isEmpty()) {
            result.stream_ = new java.util.ArrayList<java.lang.String>();
          }
          result.stream_.addAll(other.stream_);
        }
        
        if (!other.cluster_.isEmpty()) {
          if (result.cluster_.isEmpty()) {
            result.cluster_ = new java.util.ArrayList<java.lang.String>();
          }
          result.cluster_.addAll(other.cluster_);
        }
      
        return this;
      }
      
      public Builder readFrom(com.google.protobuf.gwt.shared.JsonStream input)
        throws java.io.IOException {
        
        java.util.List<java.lang.String> streamList = input.readStringRepeated(1);
        if (streamList != null) {
          addAllStream(streamList);
        }
        
        java.util.List<java.lang.String> clusterList = input.readStringRepeated(2);
        if (clusterList != null) {
          addAllCluster(clusterList);
        }
        
        return this;
      }
      
      // repeated string stream = 1;
      public java.util.List<java.lang.String> getStreamList() {
        return java.util.Collections.unmodifiableList(result.stream_);
      }
      public int getStreamCount() {
        return result.getStreamCount();
      }
      public java.lang.String getStream(int index) {
        return result.getStream(index);
      }
      public Builder setStreamIgnoreIfNull(int index, java.lang.String value) {
        if (value != null) {
          setStream(index, value);
        }
        return this;
      }
      public Builder setStream(int index, java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.stream_.set(index, value);
        return this;
      }
      public Builder addStreamIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          addStream(value);  }
        return this;
      }
      public Builder addStream(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  if (result.stream_.isEmpty()) {
          result.stream_ = new java.util.ArrayList<java.lang.String>();
        }
        result.stream_.add(value);
        return this;
      }
      public Builder addAllStreamIgnoreIfNull(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (values != null) {
          addAllStream(values);
        }
        return this;
      }
      public Builder addAllStream(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.stream_.isEmpty()) {
          result.stream_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.stream_);
        return this;
      }
      public Builder clearStream() {
        result.stream_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated string cluster = 2;
      public java.util.List<java.lang.String> getClusterList() {
        return java.util.Collections.unmodifiableList(result.cluster_);
      }
      public int getClusterCount() {
        return result.getClusterCount();
      }
      public java.lang.String getCluster(int index) {
        return result.getCluster(index);
      }
      public Builder setClusterIgnoreIfNull(int index, java.lang.String value) {
        if (value != null) {
          setCluster(index, value);
        }
        return this;
      }
      public Builder setCluster(int index, java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  result.cluster_.set(index, value);
        return this;
      }
      public Builder addClusterIgnoreIfNull(java.lang.String value) {
        if (value != null) {
          addCluster(value);  }
        return this;
      }
      public Builder addCluster(java.lang.String value) {
        if (value == null) {
    throw new java.lang.NullPointerException();
  }
  if (result.cluster_.isEmpty()) {
          result.cluster_ = new java.util.ArrayList<java.lang.String>();
        }
        result.cluster_.add(value);
        return this;
      }
      public Builder addAllClusterIgnoreIfNull(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (values != null) {
          addAllCluster(values);
        }
        return this;
      }
      public Builder addAllCluster(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.cluster_.isEmpty()) {
          result.cluster_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.cluster_);
        return this;
      }
      public Builder clearCluster() {
        result.cluster_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LoadMainPanelResponse)
    }
    
    static {
      defaultInstance = new LoadMainPanelResponse(true);
      com.inmobi.databus.visualization.shared.RequestResponse.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LoadMainPanelResponse)
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
